apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      serviceAccountName: workshopsa
      containers:
      - image: ahmedkanoun/angular-project:latest
        name: angular-project
        resources: {}
status: {}
